"""empty message

Revision ID: 02b8ed5f75e8
Revises: 2a56d7ad7d82
Create Date: 2024-10-07 17:15:26.932927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b8ed5f75e8'
down_revision = '2a56d7ad7d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('key')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('key')

    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('key')

    # ### end Alembic commands ###
