"""remove IOB

Revision ID: 4a71be583f8c
Revises: 6d514d41482b
Create Date: 2024-10-07 17:42:55.794301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a71be583f8c'
down_revision = '6d514d41482b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('key')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('key')

    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
