"""Add public key and SymmetricKeyRequest models

Revision ID: 58feac7b31b9
Revises: 99768a974c0d
Create Date: 2024-10-29 15:06:09.659235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58feac7b31b9'
down_revision = '99768a974c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
