"""add IOB

Revision ID: 6d514d41482b
Revises: 02b8ed5f75e8
Create Date: 2024-10-07 17:27:01.203133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d514d41482b'
down_revision = '02b8ed5f75e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('oid', sa.Integer(), nullable=False))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('oid', sa.Integer(), nullable=False))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('oid', sa.Integer(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('oid')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
