"""add file siz\e

Revision ID: 99768a974c0d
Revises: 9c79830bbdde
Create Date: 2024-10-07 18:52:16.178950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99768a974c0d'
down_revision = '9c79830bbdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.alter_column('data_oid',
               existing_type=postgresql.OID(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.alter_column('data_oid',
               existing_type=postgresql.OID(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.alter_column('data_oid',
               existing_type=postgresql.OID(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.alter_column('data_oid',
               existing_type=sa.Integer(),
               type_=postgresql.OID(),
               existing_nullable=False)
        batch_op.drop_column('file_size')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.alter_column('data_oid',
               existing_type=sa.Integer(),
               type_=postgresql.OID(),
               existing_nullable=False)
        batch_op.drop_column('file_size')

    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.alter_column('data_oid',
               existing_type=sa.Integer(),
               type_=postgresql.OID(),
               existing_nullable=False)
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
