"""add IOD

Revision ID: 9c79830bbdde
Revises: 4a71be583f8c
Create Date: 2024-10-07 18:04:11.070963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c79830bbdde'
down_revision = '4a71be583f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_oid', postgresql.OID(), nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_oid', postgresql.OID(), nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_oid', postgresql.OID(), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rc4_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_oid')

    with op.batch_alter_table('des_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_oid')

    with op.batch_alter_table('aes_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_oid')

    # ### end Alembic commands ###
