"""add some feature

Revision ID: a1b258e5b8c9
Revises: 
Create Date: 2024-10-30 04:52:28.924827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b258e5b8c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_request', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('access_expiry')

    # ### end Alembic commands ###
