"""add some features

Revision ID: d24e319118de
Revises: a1b258e5b8c9
Create Date: 2024-10-30 04:56:40.250516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e319118de'
down_revision = 'a1b258e5b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_access_revoked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_request', schema=None) as batch_op:
        batch_op.drop_column('is_access_revoked')

    # ### end Alembic commands ###
